spring:
  datasource:
    username: root
    password: xqs123456
    url: jdbc:mysql://localhost:3306/codingmore-mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
